Controllers (Initial Implementation)
ryanmckim/InternDB pull request #12
Opened 2023-07-08 05:04 UTC by ryanmckim

2023-07-22 09:32 UTC, Hgjnnf requested changes
Initial review done for controllers/company.ts. This is before testing it. I'm going to break the review down into smaller pieces cuz it's a big PR. More review will come

2023-07-22 09:32 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +    const companies = await companyRepository.find();
Does this ensure companies will sort itself alphabetically?

2023-07-22 09:32 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +    if (req.body.sort == "sortMostRecent") {
Let's do req.query instead of req.body because req.body is more reserved for POST requests instead of GET

2023-07-22 09:32 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +    } else {
Else should just return reviews without sorting

2023-07-22 09:32 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +    if (req.body.currency === "both") {
req.query here as well

2023-07-22 09:32 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +      company!.reviews.filter((review) => {
this filter won't change the company object. You can assign this to a variable/constant.

2023-07-22 09:32 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +      const totalSalary = company!.reviews.reduce((sum, review) => {
this needs to be changed as well cuz company is not filtered

2023-07-22 09:32 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +      company!.reviews.filter((review) => {
this can be turned into a util function because "CAD" and "USD" has the same code except for the currency.

2023-07-22 09:32 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +        avgSalary: avgSalary,
Let's also add numOfReviews to updatedCompany

2023-07-22 10:19 UTC, Hgjnnf requested changes
controllers/review.ts initial review (not yet tested)

2023-07-22 12:09 UTC, Hgjnnf requested changes
Mostly looks good. controllers/user.ts initial review done

2023-07-22 12:09 UTC, Hgjnnf commented on backend/src/controllers/user.ts
> +    user!.reviews.sort(
Should we add an option to sort mostRecent and leastRecent?

2023-07-22 12:12 UTC, Hgjnnf commented on backend/src/controllers/company.ts
> +        avgSalary: avgSalary,
Also, keep in mind that the updatedCompany should contain filtered reviews (rn it's unfiltered)

2023-07-22 12:20 UTC, Hgjnnf requested changes
errors and routes look good. Added change request for models.

2023-07-22 12:20 UTC, Hgjnnf commented on backend/src/models/Review.ts
> +  @Column({ unique: true })
userID cannot be unique because one user can post review more than once

2023-07-22 12:20 UTC, Hgjnnf commented on backend/src/models/Review.ts
> +  @Column({ unique: true })
Same here. A company can have many reviews.

2023-07-26 05:09 UTC, ryanmckim commented on backend/src/controllers/company.ts
> +    const companies = await companyRepository.find();
The DB will be sorted alphabetically at all times (updated in the API doc)

2023-09-08 05:12 UTC, Hgjnnf approved these changes
Postman tested. Approved

2023-09-08 05:14 UTC, merged