Configured routes
ryanmckim/InternDB pull request #6
Opened 2023-06-11 05:43 UTC by ryanmckim

2023-06-11 06:55 UTC, Hgjnnf requested changes
I added some comments. The routes here look good so far, but we can always add more or change them as needed. Also, we should define the higher hierarchy routes in the main index.ts file (i.e. /review, /company, /user) cuz it's kinda redundant to type /review every time.

2023-06-11 06:55 UTC, Hgjnnf commented on backend/src/routes/company.ts
> +router.route("/company/:id").put(protect, updateSalary);
Do we want to have the ability to change salary manually? Or should the reviews affect the salary?

2023-06-11 06:55 UTC, Hgjnnf commented on backend/src/routes/review.ts
> +router.route("review/:id").delete(protect, deleteReview);
Missing a / in front of the review

2023-06-11 06:55 UTC, Hgjnnf commented on backend/src/routes/review.ts
> +router.route("/review").get(protect, displayUserReview);
Let's move this to the user.ts. It should also be /user/review. Otherwise, there would be a duplicate.

2023-06-11 06:55 UTC, Hgjnnf commented on backend/src/routes/review.ts
> +router.route("/review").get(protect, displayReview);
Do we want to show all reviews? We didn't have this in the wireframe. Also, since this is to see the reviews, everyone has access to it, so we don't need protect.

2023-06-11 06:55 UTC, Hgjnnf commented on backend/src/routes/company.ts
> +router.route("/company").get(protect, displayCompanies);
Don't need protect here cuz everyone can see without logging in.

2023-06-11 06:55 UTC, Hgjnnf commented on backend/src/routes/company.ts
> +router.route("/company/:id").get(protect, displayCompany);
Same here for protect.

2023-06-11 06:55 UTC, Hgjnnf commented on backend/src/routes/user.ts
> +router.route("/user/:id").put(protect, newPassword);
Should be more descriptive. Like /user/:id/password

2023-06-11 06:55 UTC, Hgjnnf commented on backend/src/routes/user.ts
> +router.route("/user").post(protect, createUser);
Don't need protect here either

2023-06-11 07:09 UTC, ryanmckim commented on backend/src/routes/company.ts
> +router.route("/company/:id").put(protect, updateSalary);
Updating the average salary every time someone adds/updates/deletes their reviews should make it accurate I think.

2023-06-11 07:14 UTC, ryanmckim commented on backend/src/routes/review.ts
> +router.route("review/:id").delete(protect, deleteReview);
Fixed:D

2023-06-11 07:16 UTC, Hgjnnf commented on backend/src/routes/company.ts
> +router.route("/company/:id").put(protect, updateSalary);
Ok, then i think we should remove this route cuz this sounds like it's for manually changing it.

2023-06-11 07:16 UTC, ryanmckim commented on backend/src/routes/user.ts
> +router.route("/user").post(protect, createUser);
yessir:D

2023-06-11 07:16 UTC, ryanmckim commented on backend/src/routes/user.ts
> +router.route("/user/:id").put(protect, newPassword);
done:D

2023-06-11 07:19 UTC, ryanmckim commented on backend/src/routes/company.ts
> +router.route("/company").get(protect, displayCompanies);
done:D

2023-06-11 07:19 UTC, ryanmckim commented on backend/src/routes/company.ts
> +router.route("/company/:id").put(protect, updateSalary);
Sounds good.

2023-06-11 07:24 UTC, ryanmckim commented on backend/src/routes/review.ts
> +router.route("/review").get(protect, displayReview);
Done:D

2023-06-11 07:27 UTC, ryanmckim commented on backend/src/routes/review.ts
> +router.route("/review").get(protect, displayUserReview);
Done:D

2023-06-11 07:31 UTC, Hgjnnf requested changes

2023-06-11 07:31 UTC, Hgjnnf commented on backend/src/routes/user.ts
> +router.route("/company/review").get(displayReview);
why is this in the user file?

2023-06-12 03:34 UTC, Hgjnnf approved these changes

2023-06-12 03:36 UTC, merged